name: Formatting BOT

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: ./src
          clangFormatVersion: 9
          inplace: True
          style: Microsoft
      - name: Commit reformatted files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Fix formatting errors'
